// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trentinofamiglia.proto

package eu.trentorise.smartcampus.service.trentinofamiglia.data.message;

public final class Trentinofamiglia {
  private Trentinofamiglia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventoFamigliaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // required string from = 4;
    boolean hasFrom();
    String getFrom();
    
    // required string to = 5;
    boolean hasTo();
    String getTo();
    
    // required string days = 6;
    boolean hasDays();
    String getDays();
    
    // required string organization = 7;
    boolean hasOrganization();
    String getOrganization();
    
    // optional .it.sayservice.platform.core.message.POI poi = 8;
    boolean hasPoi();
    it.sayservice.platform.core.message.Core.POI getPoi();
    it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder();
  }
  public static final class EventoFamiglia extends
      com.google.protobuf.GeneratedMessage
      implements EventoFamigliaOrBuilder {
    // Use EventoFamiglia.newBuilder() to construct.
    private EventoFamiglia(Builder builder) {
      super(builder);
    }
    private EventoFamiglia(boolean noInit) {}
    
    private static final EventoFamiglia defaultInstance;
    public static EventoFamiglia getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventoFamiglia getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string from = 4;
    public static final int FROM_FIELD_NUMBER = 4;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string to = 5;
    public static final int TO_FIELD_NUMBER = 5;
    private java.lang.Object to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          to_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string days = 6;
    public static final int DAYS_FIELD_NUMBER = 6;
    private java.lang.Object days_;
    public boolean hasDays() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getDays() {
      java.lang.Object ref = days_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          days_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDaysBytes() {
      java.lang.Object ref = days_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        days_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string organization = 7;
    public static final int ORGANIZATION_FIELD_NUMBER = 7;
    private java.lang.Object organization_;
    public boolean hasOrganization() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getOrganization() {
      java.lang.Object ref = organization_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          organization_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrganizationBytes() {
      java.lang.Object ref = organization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        organization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .it.sayservice.platform.core.message.POI poi = 8;
    public static final int POI_FIELD_NUMBER = 8;
    private it.sayservice.platform.core.message.Core.POI poi_;
    public boolean hasPoi() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public it.sayservice.platform.core.message.Core.POI getPoi() {
      return poi_;
    }
    public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
      return poi_;
    }
    
    private void initFields() {
      id_ = "";
      title_ = "";
      description_ = "";
      from_ = "";
      to_ = "";
      days_ = "";
      organization_ = "";
      poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDays()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrganization()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPoi()) {
        if (!getPoi().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFromBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getToBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDaysBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getOrganizationBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, poi_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFromBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getToBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDaysBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getOrganizationBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, poi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamigliaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        days_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        organization_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia build() {
        eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia buildPartial() {
        eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia result = new eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.days_ = days_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.organization_ = organization_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (poiBuilder_ == null) {
          result.poi_ = poi_;
        } else {
          result.poi_ = poiBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia) {
          return mergeFrom((eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia other) {
        if (other == eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasDays()) {
          setDays(other.getDays());
        }
        if (other.hasOrganization()) {
          setOrganization(other.getOrganization());
        }
        if (other.hasPoi()) {
          mergePoi(other.getPoi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (!hasTo()) {
          
          return false;
        }
        if (!hasDays()) {
          
          return false;
        }
        if (!hasOrganization()) {
          
          return false;
        }
        if (hasPoi()) {
          if (!getPoi().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              from_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              to_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              days_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              organization_ = input.readBytes();
              break;
            }
            case 66: {
              it.sayservice.platform.core.message.Core.POI.Builder subBuilder = it.sayservice.platform.core.message.Core.POI.newBuilder();
              if (hasPoi()) {
                subBuilder.mergeFrom(getPoi());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPoi(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // required string from = 4;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000008);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        from_ = value;
        onChanged();
      }
      
      // required string to = 5;
      private java.lang.Object to_ = "";
      public boolean hasTo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      void setTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        to_ = value;
        onChanged();
      }
      
      // required string days = 6;
      private java.lang.Object days_ = "";
      public boolean hasDays() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getDays() {
        java.lang.Object ref = days_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          days_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDays(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        days_ = value;
        onChanged();
        return this;
      }
      public Builder clearDays() {
        bitField0_ = (bitField0_ & ~0x00000020);
        days_ = getDefaultInstance().getDays();
        onChanged();
        return this;
      }
      void setDays(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        days_ = value;
        onChanged();
      }
      
      // required string organization = 7;
      private java.lang.Object organization_ = "";
      public boolean hasOrganization() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getOrganization() {
        java.lang.Object ref = organization_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          organization_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrganization(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        organization_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrganization() {
        bitField0_ = (bitField0_ & ~0x00000040);
        organization_ = getDefaultInstance().getOrganization();
        onChanged();
        return this;
      }
      void setOrganization(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        organization_ = value;
        onChanged();
      }
      
      // optional .it.sayservice.platform.core.message.POI poi = 8;
      private it.sayservice.platform.core.message.Core.POI poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> poiBuilder_;
      public boolean hasPoi() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public it.sayservice.platform.core.message.Core.POI getPoi() {
        if (poiBuilder_ == null) {
          return poi_;
        } else {
          return poiBuilder_.getMessage();
        }
      }
      public Builder setPoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          poi_ = value;
          onChanged();
        } else {
          poiBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setPoi(
          it.sayservice.platform.core.message.Core.POI.Builder builderForValue) {
        if (poiBuilder_ == null) {
          poi_ = builderForValue.build();
          onChanged();
        } else {
          poiBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergePoi(it.sayservice.platform.core.message.Core.POI value) {
        if (poiBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              poi_ != it.sayservice.platform.core.message.Core.POI.getDefaultInstance()) {
            poi_ =
              it.sayservice.platform.core.message.Core.POI.newBuilder(poi_).mergeFrom(value).buildPartial();
          } else {
            poi_ = value;
          }
          onChanged();
        } else {
          poiBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearPoi() {
        if (poiBuilder_ == null) {
          poi_ = it.sayservice.platform.core.message.Core.POI.getDefaultInstance();
          onChanged();
        } else {
          poiBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public it.sayservice.platform.core.message.Core.POI.Builder getPoiBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getPoiFieldBuilder().getBuilder();
      }
      public it.sayservice.platform.core.message.Core.POIOrBuilder getPoiOrBuilder() {
        if (poiBuilder_ != null) {
          return poiBuilder_.getMessageOrBuilder();
        } else {
          return poi_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder> 
          getPoiFieldBuilder() {
        if (poiBuilder_ == null) {
          poiBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              it.sayservice.platform.core.message.Core.POI, it.sayservice.platform.core.message.Core.POI.Builder, it.sayservice.platform.core.message.Core.POIOrBuilder>(
                  poi_,
                  getParentForChildren(),
                  isClean());
          poi_ = null;
        }
        return poiBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.trentinofamiglia.data.message.EventoFamiglia)
    }
    
    static {
      defaultInstance = new EventoFamiglia(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.trentinofamiglia.data.message.EventoFamiglia)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026trentinofamiglia.proto\022?eu.trentorise." +
      "smartcampus.service.trentinofamiglia.dat" +
      "a.message\032\ncore.proto\"\265\001\n\016EventoFamiglia" +
      "\022\n\n\002id\030\001 \002(\t\022\r\n\005title\030\002 \002(\t\022\023\n\013descripti" +
      "on\030\003 \002(\t\022\014\n\004from\030\004 \002(\t\022\n\n\002to\030\005 \002(\t\022\014\n\004da" +
      "ys\030\006 \002(\t\022\024\n\014organization\030\007 \002(\t\0225\n\003poi\030\010 " +
      "\001(\0132(.it.sayservice.platform.core.messag" +
      "e.POI"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_trentinofamiglia_data_message_EventoFamiglia_descriptor,
              new java.lang.String[] { "Id", "Title", "Description", "From", "To", "Days", "Organization", "Poi", },
              eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.class,
              eu.trentorise.smartcampus.service.trentinofamiglia.data.message.Trentinofamiglia.EventoFamiglia.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
